# Generated by Django 2.2.6 on 2019-12-10 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0002_auto_20191210_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondent_first_name', models.CharField(max_length=50)),
                ('respondent_last_name', models.CharField(max_length=50)),
                ('respondent_address', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('complain', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.Category')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Create_Complaint_Model',
        ),
    ]
