# Generated by Django 2.2.6 on 2019-12-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20191210_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint_model',
            name='comments',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='complaint_model',
            name='resolution',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
