# Generated by Django 2.2.6 on 2019-12-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20191210_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint_model',
            name='is_canceled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint_model',
            name='is_submitted',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
