# Generated by Django 2.2.6 on 2019-12-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20191212_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_model',
            name='is_canceled',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='complaint_model',
            name='is_submitted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
