# Generated by Django 2.2.6 on 2019-12-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_auto_20191212_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_model',
            name='resolution',
            field=models.CharField(blank=True, choices=[('IN PROGRESS', 'IN PROGRESS'), ('RESOLVED', 'RESOLVED'), ('UNRESOLVED', 'UNRESOLVED')], max_length=100),
        ),
    ]
