# Generated by Django 2.2.6 on 2019-12-09 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20191208_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='logo_cover',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='logo_title',
        ),
    ]
