# Generated by Django 2.2.6 on 2019-12-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20191209_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='logo_cover',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='logo_title',
            field=models.TextField(blank=True),
        ),
    ]
