# Generated by Django 2.2.6 on 2019-12-09 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20191209_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='logo_title',
        ),
    ]
