# Generated by Django 2.2.6 on 2019-12-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_remove_baseuser_logo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='mobile_number',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='zip_code',
            field=models.CharField(max_length=4),
        ),
    ]
